import { formatCurrency } from "../utils/calculations";
import { formatDate, formatWebsite } from "../utils/formatters";

export default function DocumentPreview({ type, invoiceNumber, dueDate, company, customer, items, totals, notes, terms, taxType }) {
  return (
    <div className="w-[794px] bg-white p-10 text-slate-900">
      <div className="flex items-start justify-between border-b border-slate-200 pb-8">
        <div className="max-w-md">
          {company?.logoUrl ? <img src={company.logoUrl} alt={company.name} className="mb-4 h-20 w-20 rounded-2xl object-contain" /> : null}
          <h1 className="text-3xl font-bold">{company?.name || "Company Name"}</h1>
          <p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{company?.address || "-"}</p>
          <div className="mt-4 space-y-1 text-sm text-slate-600"><p>GSTIN: {company?.gstin || "-"}</p><p>Phone: {company?.phone || "-"}</p><p>Email: {company?.email || "-"}</p><p>Website: {company?.website ? formatWebsite(company.website) : "-"}</p></div>
        </div>
        <div className="rounded-3xl bg-slate-950 px-6 py-5 text-white"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-brand-200">{type === "invoice" ? "Tax Invoice" : "Quotation"}</p><p className="mt-3 text-2xl font-semibold">{invoiceNumber}</p><div className="mt-5 space-y-2 text-sm text-slate-200"><p>Due Date: {formatDate(dueDate)}</p><p>Tax Mode: {taxType === "igst" ? "IGST 18%" : "CGST 9% + SGST 9%"}</p></div></div>
      </div>
      <div className="mt-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Bill To</p><h2 className="mt-3 text-xl font-semibold">{customer.name || "-"}</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{customer.address || "-"}</p><div className="mt-4 space-y-1 text-sm text-slate-600"><p>Phone: {customer.phone || "-"}</p><p>Email: {customer.email || "-"}</p><p>Zip Code: {customer.zipCode || "-"}</p><p>Place of Supply: {customer.placeOfSupply || "-"}</p><p>GSTIN: {customer.gstin || "-"}</p></div></div>
      <div className="mt-8 overflow-hidden rounded-3xl border border-slate-200"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-100"><tr className="text-left text-xs font-semibold uppercase tracking-[0.2em] text-slate-500"><th className="px-4 py-4">Description</th><th className="px-4 py-4">HSN Code</th><th className="px-4 py-4">Qty</th><th className="px-4 py-4">Rate</th><th className="px-4 py-4">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item, index) => <tr key={`${item.description}-${index}`} className="text-sm text-slate-700"><td className="px-4 py-4">{item.description}</td><td className="px-4 py-4">{item.hsnCode || "-"}</td><td className="px-4 py-4">{item.quantity}</td><td className="px-4 py-4">{formatCurrency(item.rate)}</td><td className="px-4 py-4">{formatCurrency(item.total)}</td></tr>)}</tbody></table></div>
      <div className="mt-8 flex justify-end"><div className="w-full max-w-sm rounded-3xl bg-slate-50 p-6"><div className="flex items-center justify-between py-2 text-sm text-slate-600"><span>Subtotal</span><span>{formatCurrency(totals.subtotal)}</span></div><div className="flex items-center justify-between py-2 text-sm text-slate-600"><span>CGST</span><span>{formatCurrency(totals.cgst)}</span></div><div className="flex items-center justify-between py-2 text-sm text-slate-600"><span>SGST</span><span>{formatCurrency(totals.sgst)}</span></div><div className="flex items-center justify-between py-2 text-sm text-slate-600"><span>IGST</span><span>{formatCurrency(totals.igst)}</span></div><div className="mt-2 flex items-center justify-between border-t border-slate-200 pt-4 text-base font-semibold text-slate-900"><span>Total</span><span>{formatCurrency(totals.totalAmount)}</span></div>{type === "invoice" ? <><div className="flex items-center justify-between py-2 text-sm text-slate-600"><span>Payment Made</span><span>{formatCurrency(totals.paymentMade)}</span></div><div className="flex items-center justify-between py-2 text-sm font-semibold text-brand-700"><span>Balance Amount</span><span>{formatCurrency(totals.balanceAmount)}</span></div></> : null}</div></div>
      <div className="mt-8 grid grid-cols-2 gap-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Notes</p><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{notes || "-"}</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Terms & Conditions</p><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{terms || "-"}</p></div></div>
    </div>
  );
}
